"""init env harvest

Revision ID: 8df0522dd904
Revision: 
Create Date: 2026-01-10 08:16:00.063104
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8df0522dd904'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('env',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('month', sa.String(length=7), nullable=False),
    sa.Column('temperature', sa.Float(), nullable=False),
    sa.Column('humidity', sa.Float(), nullable=False),
    sa.Column('medium', sa.String(length=50), nullable=False),
    sa.Column('water_content', sa.Float(), nullable=False),
    sa.Column('illuminance', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_env_id'), 'env', ['id'], unique=False)
    op.create_index(op.f('ix_env_month'), 'env', ['month'], unique=False)
    op.create_table('harvest',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('month', sa.String(length=7), nullable=False),
    sa.Column('company', sa.String(length=100), nullable=False),
    sa.Column('crop', sa.String(length=100), nullable=False),
    sa.Column('amount_kg', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_harvest_company'), 'harvest', ['company'], unique=False)
    op.create_index(op.f('ix_harvest_crop'), 'harvest', ['crop'], unique=False)
    op.create_index(op.f('ix_harvest_id'), 'harvest', ['id'], unique=False)
    op.create_index(op.f('ix_harvest_month'), 'harvest', ['month'], unique=False)
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_harvest_month'), table_name='harvest')
    op.drop_index(op.f('ix_harvest_id'), table_name='harvest')
    op.drop_index(op.f('ix_harvest_crop'), table_name='harvest')
    op.drop_index(op.f('ix_harvest_company'), table_name='harvest')
    op.drop_table('harvest')
    op.drop_index(op.f('ix_env_month'), table_name='env')
    op.drop_index(op.f('ix_env_id'), table_name='env')
    op.drop_table('env')
    # ### end Alembic commands ###

